### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by Hazel-30** [Hazel-30/SCM_PG-03#5]
Improve the UI od the page.
![Screenshot (533)](https://github.com/Hazel-30/SCM_PG-03/assets/156660862/3a2c18f0-9a9a-438d-9f38-cc60c60e539b)

**Comment by himank2097** [comment]
Have imporved UI Elements

![image](https://github.com/Hazel-30/SCM_PG-03/assets/156660489/0cd671ae-cf83-4ed2-94a5-8506f74e4132)
